/** Books actions */
const WS_ADD_BOOK = 'WS_ADD_BOOK'
const NOTIFY_BOOK = 'NOTIFY_BOOK'

const FETCH_BOOKS = 'FETCH_BOOKS'
const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'

const POST_BOOK = 'POST_BOOK'
const POST_BOOK_SUCCESS = 'POST_BOOK_SUCCESS'

export {
  WS_ADD_BOOK,
  NOTIFY_BOOK,
  FETCH_BOOKS,
  FETCH_BOOKS_SUCCESS,
  POST_BOOK,
  POST_BOOK_SUCCESS
}
