/** Books actions */
const ADD_BOOK = 'ADD_BOOK'
const FETCH_BOOKS = 'FETCH_BOOKS'
const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'

const POST_BOOK = 'POST_BOOK'
const POST_BOOK_SUCCESS = 'POST_BOOK_SUCCESS'

export {
  ADD_BOOK,
  FETCH_BOOKS,
  FETCH_BOOKS_SUCCESS,
  POST_BOOK,
  POST_BOOK_SUCCESS
}
